Repository iiasa/ixmp, pull requests merged in 2020-08, with the labels that each got.

#352 typo in docstring reporting/computations/select()
  ixmp/reporting/computations.py
Labels: docs

#357 Avoid usage of R devtools in CI
  .github/workflows/pytest.yml
Labels: R, ci

#358 Use --no-multiarch when installing R package on Windows CI
  .github/workflows/pytest.yml
Labels: R, ci

#359 Run CI checks on Python 3.6
  .github/workflows/pytest.yml
Labels: ci

#354 Filter all data from one Scenario by a set element; add utils.diff()
  .github/workflows/lint.yml
  RELEASE_NOTES.rst
  ixmp/backend/base.py
  ixmp/backend/io.py
  ixmp/cli.py
  ixmp/core.py
  ixmp/tests/core/test_scenario.py
  ixmp/tests/test_cli.py
  ixmp/tests/test_utils.py
  ixmp/utils.py
Labels: enh

#361 Don't error on missing dim= kwarg in reporting…concat()
  ixmp/reporting/computations.py
Labels: reporting

#362 Convert some Java exceptions to RuntimeError
  RELEASE_NOTES.rst
  ixmp/backend/jdbc.py
  ixmp/tests/backend/test_jdbc.py
Labels: backend.jdbc

#363 Update documentation for v3.2
  .github/PULL_REQUEST_TEMPLATE.md
  RELEASE_NOTES.rst
  doc/source/api-backend.rst
  doc/source/conf.py
  doc/source/install.rst
Labels: R, docs

#345 Correct error in io.s_read_excel for items on multiple sheets
  RELEASE_NOTES.rst
  ixmp/backend/io.py
  ixmp/tests/backend/test_io.py
Labels: bug
