Repository iiasa/ixmp, pull requests merged in 2020-06, with the labels that each got.

#332 Add .eggs files to .gitignore
  .gitignore
Labels: bug

#330 Use GitHub Actions for CI
  .appveyor.yml
  .gitattributes
  .github/workflows/lint.yml
  .github/workflows/pytest.yml
  .gitignore
  .stickler.yml
  .travis.yml
  README.md
  RELEASE_NOTES.rst
  ci/appveyor-install.R
  ci/appveyor-install.ps1
  ci/conda-requirements.txt
  ci/coveragerc
  ci/env.sh
  ci/install-curl.sh
  ci/install-gams.sh
  ci/install-graphviz.sh
  ci/travis-before_install.sh
  ci/travis-install.sh
  ixmp/backend/io.py
  ixmp/backend/jdbc.py
  ixmp/core.py
  ixmp/reporting/quantity.py
  ixmp/tests/backend/test_jdbc.py
  ixmp/tests/conftest.py
  ixmp/tests/core/test_platform.py
  ixmp/tests/test_r.py
  setup.cfg
Labels: ci, enh

#335 Ensure setuptools-scm is installed on GH Actions runners
  .github/workflows/lint.yml
  .github/workflows/pytest.yml
Labels: ci

#317 Generalize reporting.Quantity in preparation for sparse xarray
  RELEASE_NOTES.rst
  doc/source/conf.py
  doc/source/reporting.rst
  ixmp/cli.py
  ixmp/reporting/__init__.py
  ixmp/reporting/attrseries.py
  ixmp/reporting/computations.py
  ixmp/reporting/quantity.py
  ixmp/reporting/sparsedataarray.py
  ixmp/reporting/testing.py
  ixmp/reporting/utils.py
  ixmp/testing.py
  ixmp/tests/reporting/__init__.py
  ixmp/tests/reporting/test_computations.py
  ixmp/tests/reporting/test_quantity.py
  ixmp/tests/reporting/test_reporting.py
  setup.cfg
Labels: reporting
