Repository iiasa/ixmp, pull requests merged in 2020-03, with the labels that each got.

#278 Exclude JPype 0.7.2 from CI; add python3-setuptools for TeamCity
  ci/Dockerfile
  ci/conda-requirements.txt
  ci/run.sh
  ci/teamcity/Dockerfile
  setup.py
Labels: ci

#285 Reporter.describe modified to not print by default
  ixmp/reporting/__init__.py
  ixmp/tests/reporting/test_reporting.py
Labels: reporting

#289 Transfer Excel data I/O from message_ix
  .appveyor.yml
  .travis.yml
  RELEASE_NOTES.rst
  ci/conda-requirements.txt
  doc/source/api-backend.rst
  doc/source/api-python.rst
  doc/source/api.rst
  doc/source/file-io.rst
  ixmp/backend/base.py
  ixmp/backend/io.py
  ixmp/backend/jdbc.py
  ixmp/cli.py
  ixmp/core.py
  ixmp/ixmp.jar
  ixmp/testing.py
  ixmp/tests/backend/test_base.py
  ixmp/tests/backend/test_jdbc.py
  ixmp/tests/core/test_platform.py
  ixmp/tests/core/test_scenario.py
  ixmp/tests/core/test_timeseries.py
  ixmp/tests/test_access.py
  ixmp/tests/test_cli.py
  ixmp/tests/test_utils.py
  ixmp/utils.py
  setup.py
Labels: enh

#299 Coerce CLI 'config' inputs to expected type
  ixmp/_config.py
  ixmp/cli.py
  ixmp/tests/test_config.py
Labels: bug
