Repository iiasa/ixmp, pull requests merged in 2023-08, with the labels that each got.

#490 Handling flaky tests
  ixmp/backend/jdbc.py
  ixmp/tests/backend/test_jdbc.py
  ixmp/tests/test_access.py
  ixmp/tests/test_integration.py
  ixmp/tests/test_tutorials.py
  pyproject.toml
Labels: enh, ci

#491 Adapt to new RTD configuration style
  .readthedocs.yaml
  doc/requirements.in
  doc/requirements.txt
Labels: enh, docs

#488 Avoid locking on failed operations
  RELEASE_NOTES.rst
  doc/api.rst
  ixmp/core/timeseries.py
  ixmp/testing/__init__.py
  ixmp/tests/core/test_timeseries.py
  ixmp/tests/test_utils.py
  ixmp/utils/__init__.py
  ixmp/utils/sphinx_linkcode_github.py
Labels: enh
