Repository iiasa/ixmp, pull requests merged in 2024-01, with the labels that each got.

#504 Address GC with JPype ≥1.5.0
  .github/workflows/pytest.yaml
  RELEASE_NOTES.rst
  ixmp/backend/jdbc.py
  ixmp/core/scenario.py
  ixmp/tests/backend/test_base.py
  ixmp/tests/backend/test_jdbc.py
  ixmp/tests/core/test_scenario.py
  ixmp/tests/test_cli.py
  ixmp/tests/test_model.py
  ixmp/tests/test_util.py
  pyproject.toml
Labels: bug, backend.jdbc

#502 Record Python package versions in GDX files
  README.md
  RELEASE_NOTES.rst
  doc/conf.py
  doc/reporting.rst
  ixmp/backend/jdbc.py
  ixmp/model/dantzig.gms
  ixmp/model/gams.py
  ixmp/report/operator.py
  ixmp/tests/backend/test_jdbc.py
  ixmp/tests/core/test_scenario.py
  ixmp/util/sphinx_linkcode_github.py
Labels: enh

#506 Fix Sphinx nitpicks fron message_ix docs
  RELEASE_NOTES.rst
  ixmp/backend/__init__.py
  ixmp/core/timeseries.py
  ixmp/report/operator.py
Labels: docs

#513 Advise users to check GAMS log file
  RELEASE_NOTES.rst
  ixmp/model/gams.py
  ixmp/tests/test_model.py
Labels: enh

#514 Update minimum version of genno
  RELEASE_NOTES.rst
  pyproject.toml
Labels: enh

#517 Address GitHub Actions warnings re: node.js 16
  .github/workflows/publish.yaml
  .github/workflows/pytest.yaml
  .pre-commit-config.yaml
  ixmp/tests/test_model.py
Labels: ci
